version: '3.1'  
services:
  orthanc:
    image: jodogne/orthanc-plugins:1.7.3
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
        - ./db/:/var/lib/orthanc/db/
        - ./orthanc.json:/etc/orthanc/orthanc.json
